apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hello-server-myapp
  name: hello-server-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-server-myapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-server-myapp
    spec:
      containers:
      - image: docker.pkg.github.com/ichtestemalwieder/hello-world/myapp:latest
        name: hello-server-myapp
        ports:
        - containerPort: 8080
        resources: {}


status: {}
